### ISSUE TITLE
how to use ?

### ISSUE THREAD

**Issue by Danding1314** [bbo51dog/PMLineAPI#1]

**Comment by bbo51dog** [comment]
I'm going to write a document in free time.
I'm sorry, Could you wait a moment?

**Comment by Danding1314** [comment]
OK I see

**Comment by bbo51dog** [comment]
If you are in a hurry, you may know by looking at the [Sample.php](https://github.com/bbo51dog/PMLineAPI/blob/master/sample/Sample.php)

**Comment by bbo51dog** [comment]
Please read [this](https://github.com/bbo51dog/PMLineAPI/blob/master/README.md)
